### ISSUE TITLE
Fatal error Uncaught RuntimeException: Directory name must not be empty

### ISSUE THREAD

**Issue by pdewouters** [humanmade/linter-bot#100]
Added Linter bot to a new repo, but it's failing. 
```

Failed to run hmlinter

Could not run:
Fatal error: Uncaught RuntimeException: Directory name must not be empty. in /tmp/hmlinter-standards/phpcs-latest/vendor/squizlabs/php_codesniffer/src/Util/Standards.php:93
Stack trace:
#0 /tmp/hmlinter-standards/phpcs-latest/vendor/squizlabs/php_codesniffer/src/Util/Standards.php(93): DirectoryIterator->__construct('')
#1 /tmp/hmlinter-standards/phpcs-latest/vendor/squizlabs/php_codesniffer/src/Config.php(1599): PHP_CodeSniffer\Util\Standards::getInstalledStandardDetails()
#2 /tmp/hmlinter-standards/phpcs-latest/vendor/squizlabs/php_codesniffer/src/Ruleset.php(369): PHP_CodeSniffer\Config::setConfigData('installed_paths', '../../humanmade...', true)
#3 /tmp/hmlinter-standards/phpcs-latest/vendor/squizlabs/php_codesniffer/src/Ruleset.php(200): PHP_CodeSniffer\Ruleset->processRuleset('/tmp/repos/huma...')
#4 /tmp/hmlinter-standards/phpcs-latest/vendor/squizlabs/php_codesniffer/src/Runner.php(294): PHP_CodeSniffer\Ruleset->__construct(Object(PHP_CodeSniffer\Config))
#5 /tmp/hmlinter-standards/phpcs-latest/vendor/squizlabs/p in /tmp/hmlinter-standards/phpcs-latest/vendor/squizlabs/php_codesniffer/src/Util/Standards.php on line 93
```

**Comment by pdewouters** [comment]
Oh, I think it's because the `phpcs.dist.xml` file had a value for `installed_paths` and it was incorrect. I replaced that with `dealerdirect/phpcodesniffer-composer-installer` and it runs now.
