### ISSUE TITLE
Reusing source directory causes error

### ISSUE THREAD

**Issue by rmccue** [humanmade/linter-bot#87]
Currently tracking down this error:

```
CwdError: ENOENT: Cannot cd into '/tmp/repos/humanmade-project-name-76779a9e511a3389b984170bd4bdda181466a6f0'
at er (/var/task/node_modules/tar/lib/mkdir.js:100:17)
at FSReqWrap.oncomplete (fs.js:135:15)
```

It occurs when the Lambda instance is reused by the looks of it, although I'm unable to replicate locally.

**Comment by rmccue** [comment]
Confirmed with some debugging code. First run creates `/tmp/repos/project-da96462e9a523aa98fe5f13c13d6398f6734e2bc`, second skips creation presumably because it already exists, but then fails to extract.

(Log is in `2019/01/29/[$LATEST]45877907853040bdb1b1493768ba7fae` for reference)

**Comment by rmccue** [comment]
Added more debugging code with `console.log( await pify( fs.stat )( extractDir ) );` to see why it's failing.

**Comment by rmccue** [comment]
Filed an issue with AWS to dig deeper into this.

So far as I can tell, here's what's happening:
* Lambda runs first time around and clones down the repo into the project dir
* The JS code caches (in a global variable) that the directory has been created
* Lambda deletes the repo directory (but not the parent directories?)
* On the next invocation, we use the cached file-exists value, but the directory doesn't exist now, so it fails

I don't understand why Lambda is deleting (or not preserving) the clone directory but *is* preserving the others (`/tmp/downloads`, `/tmp/repos`).
