### ISSUE TITLE
Bad credentials for some request?

### ISSUE THREAD

**Issue by rmccue** [humanmade/linter-bot#88]
```
2019-01-29T22:35:57.882Z 18facaf6-589b-4390-a4d0-c7c04d2bf30a (node:1) UnhandledPromiseRejectionWarning:
{
    "message": "Bad credentials",
    "documentation_url": "https://developer.github.com/v3"
}

at response.text.then.message (/var/task/node_modules/@octokit/rest/lib/request/request.js:78:19)
at <anonymous>
at process._tickDomainCallback (internal/process/next_tick.js:228:7)
```

(Log in `2019/01/29/[$LATEST]45877907853040bdb1b1493768ba7fae`)

**Comment by rmccue** [comment]
I haven't seen this pop back up.

**Comment by nathanielks** [comment]
It's happened again on a client repo. Re-running the check worked.
